on:
    push:
        branches:
            - webapp


jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v3

            - name: "login to Docker hub"
              run: docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.WEB_APP_PASSWORD}}
            
            - name: "Building WebApp docker image"
              run: docker build -p 9090:80 ${{ secrets.DOCKER_HUB_USERNAME }}/my-webapp .
            
            - name: "Pushing to Docker hub"
              run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-webapp